#!/bin/bash
# Emergency PostgreSQL Fix
# Generated by Technical Team

set -e

echo "🚨 EMERGENCY DATABASE FIX"
echo "========================"
echo ""

# Phase 1: Immediate Actions
echo "PHASE 1: Immediate Actions (0-15 min)"
echo "------------------------------------"

echo "1. Showing current database activity..."
psql -h localhost -U user -d destiny_team -c "
SELECT pid, usename, state, 
       NOW() - query_start as duration,
       LEFT(query, 50) as query
FROM pg_stat_activity 
WHERE datname = 'destiny_team' 
AND state != 'idle'
ORDER BY query_start;"

echo ""
echo "2. Terminating long-running queries..."
psql -h localhost -U user -d destiny_team -c "
SELECT pg_terminate_backend(pid) 
FROM pg_stat_activity 
WHERE datname = 'destiny_team' 
AND state = 'active' 
AND query_start < NOW() - interval '5 minutes';"

echo ""
echo "3. Stopping real-time processors..."
pkill -f 'helena_realtime_processor' || echo "  - helena_realtime_processor not running"
pkill -f 'realtime_md_watcher' || echo "  - realtime_md_watcher not running"
pkill -f 'morning_brief' || echo "  - morning_brief not running"

echo ""
echo "4. Cleaning GIN pending lists..."
psql -h localhost -U user -d destiny_team << 'EOF'
SELECT gin_clean_pending_list('idx_es_doc_refs_tags');
SELECT gin_clean_pending_list('idx_es_doc_refs_metadata');
VACUUM ANALYZE es_document_references;
EOF

echo ""
echo "5. Checking result..."
psql -h localhost -U user -d destiny_team -c "
SELECT COUNT(*) as active_queries 
FROM pg_stat_activity 
WHERE datname = 'destiny_team' 
AND state = 'active';"

echo ""
echo "✅ Phase 1 complete!"
echo ""
echo "Next steps:"
echo "- Run './emergency_fix.sh phase2' for stabilization"
echo "- Monitor with: watch -n 1 'psql -h localhost -U user -d destiny_team -c "SELECT COUNT(*) FROM pg_stat_activity WHERE state = active;"'"
