"""
Destiny CLI Tools - Main Entry Point
Generated by Tomasz Kamiński (Developer)
"""

import typer
from destiny_cli.commands import status, memory, setup, agent

app = typer.Typer(
    name="destiny",
    help="Command-line tools for Destiny Team Framework",
    add_completion=False
)

# Register commands
app.command(name="status")(status.status_command)

# Register sub-applications (they have multiple subcommands)
app.add_typer(memory.app, name="memory")
app.add_typer(setup.app, name="setup")
app.add_typer(agent.app, name="agent")

def main():
    """Main CLI entry point"""
    app()

if __name__ == "__main__":
    main()
