
            INSERT INTO documents (
                file_path,
                document_type,
                title,
                content_preview,
                line_count,
                created_at,
                indexed_at,
                source
            ) VALUES (
                'docs/status/MORNING_BRIEF_20251104.md',
                'status_report',
                '🌅 Morning Brief for Aleksander Nowak (Orchestrator)',
                '# 🌅 Morning Brief for Aleksander Nowak (Orchestrator)

**Date:** Tuesday, November 04, 2025  
**Time:** 09:18:47  
**Generated by:** Morning Brief Agent (Automated)

---

## 🎯 Executive Summary

Good ',
                140,
                NOW(),
                NOW(),
                'realtime_watcher'
            )
            ON CONFLICT (file_path) DO UPDATE SET
                document_type = EXCLUDED.document_type,
                title = EXCLUDED.title,
                content_preview = EXCLUDED.content_preview,
                indexed_at = NOW();
            